# Generated by Django 4.2.11 on 2024-06-24 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
