# Generated by Django 4.2.11 on 2025-01-06 01:32

import cloudinary.models
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=200)),
                ('descripción', djrichtextfield.models.RichTextField(max_length=10000)),
                ('imagen', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='imagen')),
            ],
        ),
    ]
