# Generated by Django 4.2.11 on 2025-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_remove_post_author_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='actualizado_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='blog_imagen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='extracto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='título',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
