# Generated by Django 4.2.11 on 2025-01-18 19:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
