# Generated by Django 4.2.11 on 2024-11-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-creado_el']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='clasificación',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_on',
            new_name='creado_el',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='booking',
            new_name='fecha_de_la_sesión',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='service',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='texto',
        ),
    ]
