# Generated by Django 4.2.11 on 2024-11-06 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_rename_author_review_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
