# Generated by Django 4.2.11 on 2024-11-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_creado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creado_el',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
