# Generated by Django 4.2.11 on 2024-06-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='consulta',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='read',
            new_name='leido',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nombre',
        ),
    ]
