# Generated by Django 4.2.11 on 2024-06-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='servicio',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('fecha', 'hora')},
        ),
    ]
