# Generated by Django 4.2.11 on 2024-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='nombre',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='comentarios',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='servicio',
            new_name='service',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00')], default='09:00 - 10:00', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hora',
        ),
    ]
